#!/bin/bash
# Copyright 2013 Answers for AWS LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Builds a Edda EBS volume to become the AMI
#
# This expects to run on an EC2 instance
#

# Include helper functions and variables
. _include.sh


echo
echo "Building Edda"

cat > torun <<EOF
#!/bin/bash
set -e

cd $playbooks_dir
ansible-playbook -T 120 -c local -i ../inventory/local -e 'ami_build=True' edda-ubuntu.yml
EOF

imgRunScriptAsUbuntu torun


