---
# Base playbook for Amazon Linux
- name: Base
  user: ec2-user
  sudo: True
  hosts: all
  roles:
    - { role: base, tags: ['base'] }
  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml
  
